// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _api_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on SampleRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SampleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SampleRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SampleRequestMultiError, or
// nil if none found.
func (m *SampleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SampleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = SampleRequestValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetId()); err != nil {
		err = SampleRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SampleRequestMultiError(errors)
	}

	return nil
}

func (m *SampleRequest) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *SampleRequest) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

func (m *SampleRequest) _validateUuid(uuid string) error {
	if matched := _api_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// SampleRequestMultiError is an error wrapping multiple validation errors
// returned by SampleRequest.ValidateAll() if the designated constraints
// aren't met.
type SampleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SampleRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SampleRequestMultiError) AllErrors() []error { return m }

// SampleRequestValidationError is the validation error returned by
// SampleRequest.Validate if the designated constraints aren't met.
type SampleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SampleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SampleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SampleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SampleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SampleRequestValidationError) ErrorName() string { return "SampleRequestValidationError" }

// Error satisfies the builtin error interface
func (e SampleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSampleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SampleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SampleRequestValidationError{}

// Validate checks the field values on SampleResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SampleResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SampleResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SampleResponseMultiError,
// or nil if none found.
func (m *SampleResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SampleResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return SampleResponseMultiError(errors)
	}

	return nil
}

// SampleResponseMultiError is an error wrapping multiple validation errors
// returned by SampleResponse.ValidateAll() if the designated constraints
// aren't met.
type SampleResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SampleResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SampleResponseMultiError) AllErrors() []error { return m }

// SampleResponseValidationError is the validation error returned by
// SampleResponse.Validate if the designated constraints aren't met.
type SampleResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SampleResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SampleResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SampleResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SampleResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SampleResponseValidationError) ErrorName() string { return "SampleResponseValidationError" }

// Error satisfies the builtin error interface
func (e SampleResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSampleResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SampleResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SampleResponseValidationError{}
